### ISSUE TITLE
artik530s - no SPI shown aka no /dev/spidev

### ISSUE THREAD

**Issue by andrewjaykeller** [resin-os/resin-artik#122]
Hello!

I'm trying to get the SPI port working on my eagleeye530s and am not seeing any /spidev listed under dev.

**Comment by floion** [comment]
@vicgal let's cross check this on Monday on both the official carrier and as well as on the eagle eye one

**Comment by andrewjaykeller** [comment]
Hi! I tried this on my artik 710 and spidev2.0 is showing up!

**Comment by vicgal** [comment]
Hello!

Could you please describe the flashing steps for the 530s eagleeye?

Thank you!

**Comment by andrewjaykeller** [comment]
The eagleeye has the same flashing steps as the dev board. 

1. Power off
2. SD in
3. 4th pin on 4-pin dip switch to ON position, all others to OFF
4. Power on
5. Wait 1 minute
6. Power off
7. All dip switches to OFF pos
8. Remove SD card
9. Power on

**Comment by andrewjaykeller** [comment]
@vicgal @floion any update? Would love to be able to test this code...

**Comment by vicgal** [comment]
Hi,

I just started a build with this pull request : https://github.com/balena-os/resin-artik/pull/123 and I will be able to test tomorrow. This should fix it.

**Comment by andrewjaykeller** [comment]
Cool! If I wanted to use another CS line for a secondary SPI device, how would I add a node for that?

**Comment by vicgal** [comment]
My understanding is that the Eagleye 530s has only one SPI output line: http://wiki.seeedstudio.com/Eagleye_530s/  - XSPI0
The board schematics seem to indicate that the XSPI0 signals lead to GPC9, GPC10, GPC11 and GPC12 gpios, which are mapped to the SPI2 bus of the SoC.
The other two (internal) buses of the SoC (SPI0 and SPI1) don't seem to have output pins.

Side note: If you want to have the spi device, you don't actually need my patch, just use (from the Host OS):
$ mount -o remount,rw /
$ mkdir /sys/kernel/config/device-tree/overlays/spi2
$ cd /mnt/boot/overlays/
$ cat s5p4418-artik533-compy-spi2.dtbo >  /sys/kernel/config/device-tree/overlays/spi
2/dtbo

**Comment by vicgal** [comment]
I forgot to add that the downfall for the above commands is that they are not persistent across reboot.
We are planning to open another issue that will add these types of configurations in the dashboard. This way, the spidev will be a system feature and it will be available for all the devices that you are using. Once opened I will let you know the issue number, so you can track it.

**Comment by andrewjaykeller** [comment]
@vicgal am i supposed to do the commands each time on reboot? Can i use SPI from a container after adding it in the host os?

**Comment by andrewjaykeller** [comment]
I added did the following to the HostOS and boom it worked on the HostOS but i'm not seeing it on the containers? Any advice?

**Comment by andrewjaykeller** [comment]
@vicgal when will the patch for this issue be merged? seems like @vicgal just kinda stopped working on it haha, anyone have advice for how to add this? I'm happy to work on it!

**Comment by vicgal** [comment]
Hi @andrewjaykeller ,

Sorry, got caught up in something and somehow I managed to miss your messages.
1. Yes, you should do the commands after each reboot.
2. No, you can't use the SPI from a container, /spidev will show up only in the HostOS, after the commands are typed in the HostOS terminal. Right now not all the devices that show up in the HostOS also show up in the container, and we are working on finding a generic technical solution that fixes overlay mounts.
3. Sorry, I don't have info about when this patch will be merged. It hasn't been merged so far because the patch fixes only the spidev not showing up for Artik Eagleye 530s. Users might want to activate devices on other platforms, and just like you, will probably want to do it from the container. It would be a major overhead to create custom patches to activate customized devices on demand.
Apologies again for not seeing this on time!

**Comment by andrewjaykeller** [comment]
@vicgal 

1. I want to use the [native artik libraries](https://github.com/SamsungARTIK/artik-sdk), will this work even if I don't do the commands in the HostOS?
2. This is not good
3. What device are you running the Artik 530s on that spidev is working?

This merge is holding up me from pushing this device into production so this is really a problem for me.

**Comment by vicgal** [comment]
@andrewjaykeller ,

Sorry, correction for number 2: What I meant to say is the commands I gave you won't work inside the container, but if you do them in the HostOS, then /dev/spidev2.0 will show up in the container also. 
Just tested myself. 
I used a single container application. If you are using multi container application a docker.compose file needs to be modified to allow the container to mount /dev 

1. If you don't do the commands in the HostOS then all library calls related to /dev/spidev2.0 will probably fail. 
2.
3. Sorry, didn't understand. I'm testing on a Artik 530s Eagleye.

@floion , this seems to be holdup for @andrewjaykeller, is there any way we could help him?

**Comment by andrewjaykeller** [comment]
@vicgal ah thanks for the reply

> Sorry, correction for number 2: What I meant to say is the commands I gave you won't work inside the container, but if you do them in the HostOS, then /dev/spidev2.0 will show up in the container also.

Awesome, I understand. There is some code i can do access the hostos from a container.

Okay cool, you're using the same board.

**Comment by floion** [comment]
Hi @andrewjaykeller is it clear for you on how to do it based on what @vicgal mentioned at https://github.com/balena-os/balena-artik/issues/122#issuecomment-442074693 ?

**Comment by andrewjaykeller** [comment]
@floion I'm not too sure, I have the container ready to go, but how am i supposed to make those HostOS calls from the c file in the container? How is this repeatable? Sorry @vicgal I thought this would be easier but from c it seems tough

**Comment by andrewjaykeller** [comment]
Do you foresee using [dbus](https://www.balena.io/docs/learn/develop/runtime/#dbus-communication-with-host-os) to execute this command?

**Comment by andrewjaykeller** [comment]
Hey team! I was able to get this working via the suggestions and the HostOS. The good part is that the device is decent for development because the container can restart. I have noticed significant degregation in performance running in this system over running the same code in the Ubuntu firmware that ships with the headwear. Any idea what the root cause of this performance degradation is? Should I open a new issue?

**Comment by vicgal** [comment]
Hi @andrewjaykeller ,

We have a (free) support forum [1] where you can describe in detail the problems you're facing. I'm suggesting the support because the issues you have might be out of our knowledge scope or time bandwidth. Some people there work on your timezone and might help you with all types of issues from architectural down to hardware-on-demand.  
If you still have troubles moving the device in production, or if you have holdups because of not being able to use the spidev,  we can merge the patch referred in this issue.

I propose to keep github for punctual and precise issues.

[1] https://forums.balena.io/c/balena-os

**Comment by andrewjaykeller** [comment]
Understood, @vicgal 

I would love the merge referenced in this issue to be merged, can we please close this issue once it's merged?

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-artik/pull/126
